### ISSUE TITLE
As a professor, I want to use a mock Q/A system with short answer choices so I can accept short answer responses from students as well.

### ISSUE THREAD

**Issue by Eddet236** [cse442-spring-2020-offering/cse442-semester-project-not-the-droids-you-are-looking-for#15]
Acceptance Test: Use a mock GUI to enter short answer questions for the class to answer.

**Comment by brandonaclarke** [comment]
Tasks:
Create an option for the instructor of the course to choose an answer style that collects data on the students answers instead of holding the correct answer in a database.
We can use different colors or different fonts/font sizes to show common/popular answers from students in the class.

Acceptance Test:
Post a question and examine the page that displays after the students' answers are collected.
